// automatically generated by the FlatBuffers compiler, do not modify

package com.treebo.UserData;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class User extends Table {
  public static User getRootAsUser(ByteBuffer _bb) { return getRootAsUser(_bb, new User()); }
  public static User getRootAsUser(ByteBuffer _bb, User obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public User __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short id() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public byte age() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte gender() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 1; }
  public String company() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer companyAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }

  public static int createUser(FlatBufferBuilder builder,
      short id,
      int nameOffset,
      byte age,
      byte gender,
      int companyOffset) {
    builder.startObject(5);
    User.addCompany(builder, companyOffset);
    User.addName(builder, nameOffset);
    User.addId(builder, id);
    User.addGender(builder, gender);
    User.addAge(builder, age);
    return User.endUser(builder);
  }

  public static void startUser(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addId(FlatBufferBuilder builder, short id) { builder.addShort(0, id, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addAge(FlatBufferBuilder builder, byte age) { builder.addByte(2, age, 0); }
  public static void addGender(FlatBufferBuilder builder, byte gender) { builder.addByte(3, gender, 1); }
  public static void addCompany(FlatBufferBuilder builder, int companyOffset) { builder.addOffset(4, companyOffset, 0); }
  public static int endUser(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

