// automatically generated by the FlatBuffers compiler, do not modify

package com.treebo.UserData;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserList extends Table {
  public static UserList getRootAsUserList(ByteBuffer _bb) { return getRootAsUserList(_bb, new UserList()); }
  public static UserList getRootAsUserList(ByteBuffer _bb, UserList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public UserList __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public User userList(int j) { return userList(new User(), j); }
  public User userList(User obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int userListLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createUserList(FlatBufferBuilder builder,
      int userListOffset) {
    builder.startObject(1);
    UserList.addUserList(builder, userListOffset);
    return UserList.endUserList(builder);
  }

  public static void startUserList(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addUserList(FlatBufferBuilder builder, int userListOffset) { builder.addOffset(0, userListOffset, 0); }
  public static int createUserListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startUserListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endUserList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishUserListBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

